version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
    # networks:
    #   - network
    # restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - ./web:/var/www/html
    # networks:
    #   - network
    # restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    # networks:
    #   - network
    # restart: always

networks:
  network:
    driver: bridge