CREATE DATABASE IF NOT EXISTS wordpress;
ALTER USER 'root'@'localhost' IDENTIFIED BY '1234';
CREATE USER IF NOT EXISTS 'dximenez'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'dximenez'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;