CREATE DATABASE IF NOT EXISTS ${DB_DATABASE};
ALTER USER 'root'@'localhost' IDENTIFIED BY '${DB_ROOT_PASSWORD}';
CREATE USER IF NOT EXISTS '${DB_USER_NAME}'@'%' IDENTIFIED BY '${DB_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${DB_USER_NAME}'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;